name = "MagnonRenormalization"
uuid = "bd1e1d5b-a5ec-4a3d-b4a5-f136a464cbd0"
authors = ["YaozhenghangMa <Yaozhenghang.Ma@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Bravais = "ada6cbde-b013-4edf-aa94-f6abe8bd6e6b"
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
QuantumLattices = "78ae1a1f-1d5d-5174-b61c-66e31b2346dc"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
